### PR TITLE
Update out of sync exercises

### LINKED ISSUE #660: Out of sync practice exercises
Out of sync practice exercises have been detected:

Command: `configlet sync --tests --docs --metadata --filepaths`

Output: 
```
Checking exercises...
[warn] docs: instructions unsynced: roman-numerals
[warn] luhn: missing 1 test case
       - invalid long number with a remainder divisible by 5 (7e7c9fc1-d994-457c-811e-d390d52fba5e)
[warn] some exercises have unsynced docs
[warn] some exercises are missing test cases
```

### PR DESCRIPTION
**Pull request by verdammelt**
## Summary

This syncs the `roman-numerals` and `luhn` exercises.

Fixes #660.

## Checklist
- [X] If docs where changed run `./bin/configlet generate` to ensure all documents are properly generated.
- [x] CI is green

### CODE REVIEW

**Review by m-dango — APPROVED** [review]

**Comment by verdammelt** [comment]
Thanks @m-dango ... sadly your approval doesn't seem sufficient to let me merge :(

**Comment by verdammelt** [comment]
@ErikSchierboom I had thought at a review by someone from the reviewers group would have been sufficient to allow merging of this PR but that didn't seem to work. Perhaps the reviewer needs to have particular permissions to this repo?

**Comment by m-dango** [comment]
^ This also happened in the perl repo recently, I'm not sure what's changed?
https://github.com/exercism/perl5/pull/465

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom I had thought at a review by someone from the reviewers group would have been sufficient to allow merging of this PR but that didn't seem to work. Perhaps the reviewer needs to have particular permissions to this repo?

Ah yes, we might want to tweak this for repos with just one maintainer. CC @iHiD 

> ^ This also happened in the perl repo recently, I'm not sure what's changed?
https://github.com/exercism/perl5/pull/465

We've ran a script to homogenize branch protections across all active track repos. If you're on Slack, we have a message here: https://exercism-team.slack.com/archives/GC3K95MRR/p1656674597997599

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
