### PR TITLE
Move some docs for cli users

### LINKED ISSUE #428: Extract track-specific help instructions from `config/exercise_readme.go.tmpl`
Each track needs a file that contains track-specific instructions on how to get help. The contents of this document are only presented to the student when using the CLI. This file lives at `exercises/shared/.docs/help.md`. **You almost certainly already have this information, but need to move it to the correct place.**

For v2 tracks, this information was (usually) included in the readme template found at `config/exercise_readme.go.tmpl`. As such, tracks can extract the help instructions from the `config/exercise_readme.go.tmpl` file to the `exercises/shared/.docs/help.md` file.

See https://github.com/exercism/csharp/pull/1557/files for an example PR.

# Tracking

https://github.com/exercism/v3-launch/issues/50

### LINKED ISSUE #429: Extract track-specific test instructions from `config/exercise_readme.go.tmpl`
Each track needs a file that contains track-specific instructions on how to manually run the tests. The contents of this document are only presented to the student when using the CLI. This file lives at `exercises/shared/.docs/tests.md`. **You almost certainly already have this information, but need to move it to the correct place.**

For v2 tracks, this information was (usually) included in the readme template found at `config/exercise_readme.go.tmpl`. As such, tracks can extract the test instructions from the `config/exercise_readme.go.tmpl` file to the `exercises/shared/.docs/tests.md` file.

See https://github.com/exercism/csharp/pull/1557/files for an example PR.

# Tracking

https://github.com/exercism/v3-launch/issues/51

### PR DESCRIPTION
**Pull request by TheLostLambda**
I think we might need to change `help.md` a little bit? Particularly with some links that aren't just to v2 Exercism stuff. Any ideas what to add @verdammelt ?

Closes #428
Closes #429

### CODE REVIEW

**Comment by verdammelt** [comment]
The old doc pointed at some documents which could be found 'in the side bar'. The new site has those docs in a URL like:

https://exercism.lol/docs/tracks/common-lisp

I'm going to ask Erik over on the linked issue #428 for recommendations on handling those links.

**Comment by verdammelt** [comment]
> Any ideas what to add @verdammelt ?

I suggest pointing people to the Lisp Discord, specifically the `beginner-questions` and `common-lisp` channels there. I lurk there and they seem to be generally a friendly and helpful bunch.

(If pointing to `beginner-questions` I think we should provide guidance to specify that any question is about "Common Lisp" since that channel is for beginners of any "Lisp".)

**Comment by verdammelt** [comment]
@TheLostLambda I hope you don't mind but I pushed a couple commits with an additional section on where to look for help (but it has a missing link - i know - working on it) and fixing a link to the track documentation page.

If you think they are OK I suggest we merge this (hopefully after i fix the missing link problem - but even without... to keep things moving along.

**Comment by verdammelt** [comment]
Note: build is failing because key-feature icons are incorrect. This is being corrected by #433.

**Comment by TheLostLambda** [comment]
Thanks for doing some work on this! Is the Online Communities a replacement for the Discord link you were thinking about? Should we also link to some of the online resources like the spec or PCL?

**Comment by verdammelt** [comment]
@TheLostLambda the spec & PCL are linked to in our track's guides/resources which is already linked in the document. Perhaps later we can review the docs a bit more and decide which items from the 'awesome list' should be included in the track docs and which should just be a link to the 'awesome list'.

**Pull request merged**
