### PR TITLE
Fixed spelling error

### PR DESCRIPTION
**Pull request by PaulT89**
element -> elements

### CODE REVIEW

**Comment by verdammelt** [comment]
Thanks for catching this!

Unfortunately that file you edited is actually generated. The file you want to edit is `concepts/arrays/introduction.md`. Then, if you could, run `./bin/configlet generate` to update this PR.

I need to add information about this step to the README and a PR template - so my apologies for giving you more work when you were just trying to help.

**Comment by PaulT89** [comment]
Okay, I'll do that now.  I'm brand new to github, so I might take my time with it, but I think I'll be able to figure this out.

**Comment by verdammelt** [comment]
No problem. The `./bin/configlet generate` is just some stuff we do here on exercism - not github-y or lisp-y.

The instructions, in case you want to give it a try is to run `./bin/fetch-configlet` which downloads the latest version of `configlet` and then you run `./bin/configlet generate`.

But I'll see about taking care of updating these PRs for now.

**Comment by verdammelt** [comment]
Closing this PR as it was already fixed in another PR.

Thanks again for catching these.

**Pull request closed without merging**
