### PR TITLE
Ensure all exercises have a UUID.

### PR DESCRIPTION
**Pull request by verdammelt**

### CODE REVIEW

**Review by TheLostLambda — APPROVED** [review]
Looks pretty good an I'm eager to get this fixed, but does beta mean these non-existent exercises will be visible to everyone? Maybe it would be better if they were marked WIP so only we saw them.

I think that's how those tags worked, but I can't find the docs at the immediate moment.

**Comment by verdammelt** [comment]
Good catch about the status - the docs seem to agree that we should set those statuses to WIP and so i did.

**Comment by TheLostLambda** [comment]
Looks great! Thanks for doing this!

**Comment by iHiD** [comment]
A step forward! Nice work, both :)

**Pull request merged**
