### PR TITLE
[v3] Move Practice Exercise example files to .meta directory

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The example implementation files for Practice Exercises should be located in the `.meta` directory. Besides being consistent with Concept Exercises, it also has the added benefit that no extra configuration is needed to prevent the example file from being downloaded to the student (as files in the `.meta` directory are never downloaded).

See [the spec](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-example-implementation).

This PR attempts to detect these example files and move them to the exercise's `.meta` directory.

Note that this change will likely break your CI, so feel free to either merge this and fix the build later, or push a fix to this PR.  

## Tracking

https://github.com/exercism/v3-launch/issues/18

### CODE REVIEW

**Comment by verdammelt** [comment]
[sigh] It doesn't change any of the config files so CI broken again.

**Comment by ErikSchierboom** [comment]
@verdammelt Ah sorry about that. I'll try and update.

**Comment by verdammelt** [comment]
@ErikSchierboom thanks - if you can't I can do it myself - but not until this evening.

**Comment by ErikSchierboom** [comment]
@verdammelt Updated

**Review by TheLostLambda — APPROVED** [review]
Hey! I can pretend to be helpful! This looks good to me :slightly_smiling_face: Thank you both!

**Comment by verdammelt** [comment]
@ErikSchierboom thanks for updating
@TheLostLambda thanks for pretending to be useful :)

**Comment by ErikSchierboom** [comment]
I love pretending to be useful!

**Pull request merged**
