### PR TITLE
Utility to generate exercises

### PR DESCRIPTION
**Pull request by verdammelt**
This is still WIP quality - but perhaps could be useable with some care.

### CODE REVIEW

**Comment by wobh** [comment]
This is very exciting! Can you generate a new exercise to show it works?

**Comment by verdammelt** [comment]
That is my plan. It will flush out problems (as it already has). @wobh do you have an exercise you'd like me to try?

**Comment by verdammelt** [comment]
Example exercise being set up via this code: https://github.com/verdammelt/common-lisp/pull/1

**Comment by wobh** [comment]
That's really excellent. Nice work!

**Comment by verdammelt** [comment]
yay!

**Comment by verdammelt** [comment]
Thanks @wobh for merging - been busy!

**Pull request merged**
