### PR TITLE
Missing Test Cases

### PR DESCRIPTION
**Pull request by serialhex**
This is to help close Issue #668.  Right now I'm just going through and adding these one-by-one in a commit, there are a few that will be here:

* Armstrong Numbers (the initial one)
* Crypto-Square
* ~~Gigaseconds~~ (How the function takes parameters it will not mutate the input)
* Matching Brackets
* Roman Numerals
* Say
* Word Count

These are the ones that I'm seeing when I run `configlet sync --tests --docs --metadata --filepaths` like the bot suggests.  I'll probably get to fixing the docs warning too, but that's another PR.

When done a `hacktoberfest-accepted` label would be nice, thanks!

### CODE REVIEW

**Comment by verdammelt** [comment]
Thanks for this work - it was on my list - but always something else do to :(

BTW: gigasecond is deprecated as a practice exercise; the track has a version of it as a concept exercise.

If configlet is telling us that a deprecated exercise is out of sync - that sounds annoying. I'd think it should not tell us about them. I'll have to look into that.

**Comment by serialhex** [comment]
@verdammelt Just wait until it's all done, I'm planning on finishing it all today, and it shouldn't take too long to do.  Just gotta wake up & have coffee ya know?

**Comment by serialhex** [comment]
@verdammelt configlet hasn't finished checking all the things, but assuming that it does comes back green this is done.  Let me know if there are any changes you would like for me to make, including making a dummy test case for Gigasecond to silence the warning.

**Comment by verdammelt** [comment]
@serialhex I'll try to take the time to review tonight (currently it is 11:15 Eastern where I am). I'm not sure what is going on with the configlet action - they seem to hav run successfully but here in the PR it is showing not completed. I tried re-running it and that succeeded - but still no change here...

**Comment by serialhex** [comment]
At @ee7's suggestion, pushed a simple PR adding newlines to files that didn't end with trailing newlines.  Seems to have fixed the error.  This PR should be good.

**Review by verdammelt — APPROVED** [review]

**Comment by verdammelt** [comment]
Everything looks good. Thanks again @serialhex

**Pull request merged**
