### PR TITLE
Give a bit of a hint about how DEFUNs are written

### LINKED ISSUE #683: socks-and-sexprs exercise: stub file needs more guidance for lisp newbies
As a newbie, I was having tremendous difficulty with the very first task on this exercise until I finally figured out where to put the symbol

```lisp
;; Evaluates to some symbol (not a keyword)
(defun lennys-favorite-food ())
```
Looking at that with newcomer eyes, where is the symbol supposed to go? Inside the empty parens is the most "obvious" place.

I had to reread the About Expressions text a few times before I realized the empty parens are the argument list.

I think
* the Expressions doc needs more guidance about `defun` 
* the stub file could add helpful comments:
  ```lisp
  ;; Evaluates to some symbol (not a keyword)
  (defun lennys-favorite-food ()
    ; your symbol goes here
  )
  ```

### PR DESCRIPTION
**Pull request by verdammelt**
## Summary

Fixes #683 by adding a small hint for the student.

## Checklist
- [x] If docs where changed run `./bin/configlet generate` to ensure all documents are properly generated.
- [x] CI is green

### CODE REVIEW

**Comment by glennj** [comment]
I would add the hints for every function. Since the focus is on atoms and conses, I think it's OK to hold the student's hand when it comes to defining the functions. Consider that this might be a student's very first time ever creating Lisp code: make it as gentle as possible.

I have fairly strong opinions about this: I'm currently in the process of writing concepts and exercises for `jq`

**Comment by verdammelt** [comment]
@glennj I updated the remaining stub function bodies to contain a comment directing the student to where they put their code. What do you think?

**Comment by glennj** [comment]
> @glennj I updated the remaining stub function bodies to contain a comment directing the student to where they put their code. What do you think?

Yes, that's exactly what I was thinking of. Fantastic!

**Comment by glennj** [comment]
I was just reading https://exercism.org/blog/freeing-our-maintainers and https://forum.exercism.org/t/freeing-our-maintainers-exercism-wide-changes-to-track-repositories/1109

In light of that, and I may have a lot of feedback as I progress throught the syllabus, how would you like to receive that feedback? In the forum? As issues here? Are you receptive if I open PRs?

**Comment by verdammelt** [comment]
I'd be happy with feedback as issues. While I am trying to look at the forum periodically I'm not always successful; while here issues are forwarded to me in email which works best for my workflow.

BTW: do you have the power to approve this PR or shall I tag someone who can?

**Review by kotp — APPROVED** [review]
The changes explicitly state what is expected.

Good for beginners.

**Pull request merged**
