### PR TITLE
Rename track to common-lisp instead of lisp

### PR DESCRIPTION
**Pull request by kytrinyx**
Per https://github.com/exercism/meta/issues/10

### CODE REVIEW

**Comment by verdammelt** [comment]
@kytrinyx any Exercism-as-a-whole reason to wait on this PR? Or can we just merge it?

**Comment by kytrinyx** [comment]
Nope—merge at will!

Everything is running either way.

**Comment by verdammelt** [comment]
Done! 🤞

**Comment by kytrinyx** [comment]
Awesome. I'll deploy in a few hours (if something went wrong right now I wouldn't be able to deal with it).

**Comment by kytrinyx** [comment]
By "a few hours" I clearly meant "tomorrow". Yesterday turned out to be complicated. I'm deploying now!

**Pull request merged**
