### PR TITLE
Fix the getting started/help guide links to be correct

### PR DESCRIPTION
**Pull request by azrazalea**
Guess: At one point this track was called lisp not common-lisp.

### CODE REVIEW

**Comment by azrazalea** [comment]
The travis build failure is due to unrelated issues with clisp. I will take a look at fixing them if I have time.

**Comment by azrazalea** [comment]
Triggering rebuild via close/open PR since it looks like this may just be a temporary error with roswell.

**Comment by azrazalea** [comment]
Running again did not help and roswell installs clisp fine locally using what looks like the same steps. Not sure if that `.tar.gz` is getting deleted after being downloaded or if something else is going on.

**Comment by verdammelt** [comment]
RE: your guess: quite right it was. Renamed it to be more specific. But not after lots of links etc. were embedded everywhere. Thank you for this PR.

The roswell failure is annoying but obviously not caused by this PR.

**Comment by azrazalea** [comment]
@verdammelt I did not! Trying to do so to verify the results are the same, and I found https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md which appears to be missing the section on configlet (found that link via the README.md in this repository). 

I played around with it a bit and not getting `configlet generate` to work right. Can you point me to the docs?

**Comment by verdammelt** [comment]
re: point you to the docs - I don't know if I can! :/

How about I merge this PR later (tonight) and then we'll do a little clean-up on any remaining things.

**Comment by verdammelt** [comment]
Maybe this doc can help: https://github.com/exercism/configlet/blob/master/README.md

**Comment by azrazalea** [comment]
With the help of that document I:

1. Cloned the `problem-specifications` to be a sibling of the `common-lisp` folder
2. With my pwd being the `common-lisp` folder I ran:
    ```
    bin/configlet generate . --spec-path ../problem-specifications
    ```

With this, a couple changes were made. One removed an actual line from a README.md, the other added trailing whitespace (which my editor auto removes so may have been due to my changes).

Comitting these for your perusal @verdammelt

**Comment by verdammelt** [comment]
Thank you. I think it is fishy that the bob exercise was changed slightly - I'll investigate after merging this. So I'm going to merge - but might have a bit more conversation here if I need your help to figure out what happened. OK?

**Comment by verdammelt** [comment]
Well - everything looks good. Thanks!

**Pull request merged**
