### PR TITLE
Create CI.yml

### PR DESCRIPTION
**Pull request by verdammelt**
ref: #291

### CODE REVIEW

**Comment by verdammelt** [comment]
Closing because I am going to do this experimentation on my fork.

**Comment by iHiD** [comment]
@verdammelt:
```
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
```

You might want to lock in the branches like this so that tests on push or PRs are only run against master (rather than pushing to any branch)

**Comment by iHiD** [comment]
(This avoids it running twice for every push you make to a PR - once for the branch and once for the PR)

**Comment by verdammelt** [comment]
I'd think i'd want it run on push to any branch. but i guess only requests to pull to master makes sense.

**Pull request closed without merging**
