### PR TITLE
adding collatz-conjecture

### PR DESCRIPTION
**Pull request by Average-user**
Just trying to decrease the amount of Unimplemented exercises on Common Lisp

### CODE REVIEW

**Comment by verdammelt** [comment]
Looks like the CI build failed during the SBCL build - but it failed while it was setting things up not while running the tests. I've kicked it off again - hopefully it will be green and we can merge this.

Thanks!

**Comment by verdammelt** [comment]
Hmm, still failed - but the code ran fine for me in SBCL. I guess we have a problem with the CI build 😞 

I'll merge this PR.  Thanks again.

**Comment by Average-user** [comment]
Yeah, the failure did not have to do with the code, i think

**Comment by Average-user** [comment]
It's fine if i implement another exercise, or should i wait until the problem gets fixed?

**Comment by verdammelt** [comment]
Another exercise?! Go for it! I'm packing-moving-unpacking for the next week - so my responses might be a bit... slow. Please be patient.

**Comment by Average-user** [comment]
Don't worry. I have no rush.

**Pull request merged**
