### PR TITLE
Syncing exercises from problem-specifications

### LINKED ISSUE #718: Out of sync practice exercises
Out of sync practice exercises have been detected:

Command: `configlet sync --tests --docs --metadata --filepaths`

Output: 
```
Checking exercises...
[warn] docs: instructions unsynced: binary-search
[warn] docs: instructions unsynced: darts
[warn] docs: instructions unsynced: largest-series-product
[warn] docs: instructions unsynced: pangram
[warn] docs: introduction unsynced: pangram
[warn] docs: instructions unsynced: secret-handshake
[warn] docs: instructions unsynced: sieve
[warn] docs: introduction missing: sieve
[warn] docs: instructions unsynced: two-fer
[warn] strain: missing 14 test cases
       - keep on empty list returns empty list (26af8c32-ba6a-4eb3-aa0a-ebd8f136e003)
       - keeps everything (f535cb4d-e99b-472a-bd52-9fa0ffccf454)
       - keeps nothing (950b8e8e-f628-42a8-85e2-9b30f09cde38)
       - keeps first and last (92694259-6e76-470c-af87-156bdf75018a)
       - keeps neither first nor last (938f7867-bfc7-449e-a21b-7b00cbb56994)
       - keeps strings (8908e351-4437-4d2b-a0f7-770811e48816)
       - keeps lists (2728036b-102a-4f1e-a3ef-eac6160d876a)
       - discard on empty list returns empty list (ef16beb9-8d84-451a-996a-14e80607fce6)
       - discards everything (2f42f9bc-8e06-4afe-a222-051b5d8cd12a)
       - discards nothing (ca990fdd-08c2-4f95-aa50-e0f5e1d6802b)
       - discards first and last (71595dae-d283-48ca-a52b-45fa96819d2f)
       - discards neither first nor last (ae141f79-f86d-4567-b407-919eaca0f3dd)
       - discards strings (daf25b36-a59f-4f29-bcfe-302eb4e43609)
       - discards lists (a38d03f9-95ad-4459-80d1-48e937e4acaf)
[warn] some exercises have unsynced docs
[warn] some exercises are missing test cases
```

### PR DESCRIPTION
**Pull request by verdammelt**
Fixes #718.

### CODE REVIEW

**Comment by verdammelt** [comment]
Could I get a review from @exercism/reviewers ? Thanks!

**Comment by verdammelt** [comment]
Thanks @ee7

**Review by kotp — APPROVED** [review]

**Comment by verdammelt** [comment]
Thanks @ee7  & @kotp but it seems neither of your approvals is sufficient so I've tagged @kytrinyx & @ErikSchierboom (calling in the big names!) Thanks.

**Comment by verdammelt** [comment]
> If I recall correctly, it's something like "the [common-lisp team](https://github.com/orgs/exercism/teams/common-lisp) has >=2 members, so the reviewers team doesn't have write access by default". But a track may be able to opt-in to reviews from the reviewers team being sufficient.

Hmm I think it is just me again on the track - so I'll find and update the maintainers list...

**Pull request merged**
