### PR TITLE
Move to a simpler test function in existing exercises

### LINKED ISSUE #417: Simplify the V3 Test Files
The V3 `run-tests` function no longer needs to be used by the test-runner, only the learner. We could simplify all of the V3 tests to have the same `run-tests` function as V2 – making things consistent and simpler.

Here is the proposed replacement:

```lisp
(defun run-tests (&optional (test-or-suite 'robot-simulator-suite))
  "Provides human readable results of test run. Default to entire suite."
  (run! test-or-suite))
```

### PR DESCRIPTION
**Pull request by TheLostLambda**
Closes #417

### CODE REVIEW

**Comment by TheLostLambda** [comment]
@verdammelt Did we lose the exercise generator somewhere along the way? The one that took the template files and generated the scaffolding for a new concept exercise?

**Comment by verdammelt** [comment]
Not "lost" but I doubt it works correctly anymore. I think I opened a issue to make a new one or get the existing working again.

**Comment by TheLostLambda** [comment]
Ah, that's fair. I just couldn't find it anywhere in the repository! That makes more sense :)

**Comment by verdammelt** [comment]
Looks like I removed the generator in commit 6833bc3.

**Review by verdammelt — APPROVED** [review]
This looks good to me.

**Comment by TheLostLambda** [comment]
> Looks like I removed the generator in commit [6833bc3](https://github.com/exercism/common-lisp/commit/6833bc31baa22b9451e188ae6eacd1289f1a2be5).

Huh, I don't even think this was the one I was thinking about! I think I had in mind the little template thing I wrote just for v3 concept exercises! I suppose we have a few generators kicking around now :sweat_smile: 

Probably best to continue this hunt elsewhere though as I think I'll merge this :)

**Pull request merged**
