### PR TITLE
Update workflows to trigger on master push and all PR

### PR DESCRIPTION
**Pull request by verdammelt**
Based upon comments upon PR #294.

### CODE REVIEW

**Comment by verdammelt** [comment]
@cmccandless @SaschaMann would like your reviews on this. I believe it addresses your comments from PR #294 about when the workflows should be triggered.

**Review by cmccandless — APPROVED** [review]
LGTM

**Review by SaschaMann — APPROVED** [review]
LGTM too

**Comment by SaschaMann** [comment]
Correction: I was wrong about them being duplicate builds, they're actually slightly different. See: https://github.com/exercism/problem-specifications/pull/1725#issuecomment-715926411

**Pull request closed without merging**
