### PR TITLE
Quieten the build.

### PR DESCRIPTION
**Pull request by verdammelt**
I don't like noisy builds so I squelched some of the noise.

I worry though that by muffling style warnings (these are the compiler notes from SBCL) we might actually be missing something...

Thoughts?

### CODE REVIEW

**Review by TheLostLambda — COMMENTED** [review]
Hmm, I'm a bit divided on this as well. Do you have a comparison of the CI outputs?

I think that it's nice to have a quiet, clean build, but warnings are legitimately helpful to have. Maybe warnings could have their own, separate CI job? Or maybe it's a flag for this one?

Ultimately though, I'm fine with whichever you decide to prefer (I am curious about the warnings we are squelching though)

**Comment by verdammelt** [comment]
The style warnings we don't want are the ones creaetd when you load the stub solution file - this file generates a lot of unused variable etc. type message.s

The style warnings I think we want are from the test and example/exampler files.

**Comment by TheLostLambda** [comment]
Ah! I didn't quite catch that nuance the first time around! Yeah, I actually think this is a good idea then. I think if there are legitimate style errors in things like example files (I don't know if those are actually tested here?) that would be something we could catch during local development.

I think this is a good idea for the time being!

**Review by TheLostLambda — APPROVED** [review]

**Comment by verdammelt** [comment]
My worry about silencing useful warnings (such as from test files or example/exemplar files) worries me - but hopefully we'd see those in development. But I'll also add to my todo list a sort of 'linter' CI that could go through those files and load them out and perhaps fail if there are warnings, at least report them.

**Pull request merged**
