### PR TITLE
replaced `is-valid` with `validp` in exercise `luhn`

### PR DESCRIPTION
**Pull request by chuchana**

### CODE REVIEW

**Comment by TheLostLambda** [comment]
Hi @chuchana ! This is a good catch! Using the predicate naming seems much more idiomatic! Do you prefer `valid-p` over `vaildp`?

**Comment by TheLostLambda** [comment]
Additionally, I think we will need to update the naming in `exercises/luhn/example.lisp` to get the Travis build passing :)

**Comment by chuchana** [comment]
Hi, thanks, but I didn't catch it, the mentor @verdammelt did.

I find `valid-p` more readable, though I think the convention is to just append a `p` for short/single words. Should I change it to `validp`?

**Comment by TheLostLambda** [comment]
I'm not too fussed about `valid-p` vs `validp`, but glancing through the standard, it seems like `validp` is more idiomatic here. I might lean towards `validp` for that reason, but I'm alright with merging either :) Just let me know!

**Comment by TheLostLambda** [comment]
Looks good to me!

**Comment by verdammelt** [comment]
@chuchana thanks for contributing to the track!

@TheLostLambda thanks for handling the merging.

**Pull request merged**
